#!/bin/bash

# list of the files and folders to be ignored
ignoreList=("$0" ".git/" "README.md")

# loop though all the files and folders in the directory
for file in *; do
  # if the file is not in the ignore list then
  if [[ ! " ${ignoreList[*]} " =~ $file ]]; then
    # symlink the file into $HOME/bin/
    ln -sf $PWD/$file $HOME/bin/$file
  fi
done
