#!/bin/bash

# checks to see if a filename was given to the command
if [ -z "$1" ]; then
  echo "No filename was given"
else
  # if a filename was given, in $PWD touch the filename with the time and date in UTC
  # added to the end of it
  touch "$PWD"/"$1"-"$(date -u +%R_%d-%m-%yUTC)".md
fi

