#!/bin/bash
cd $HOME/repos/github/
for folder in *; do
  printf "\033[38;5;197m"
  printf "\n----------"
  printf "Checking $folder----------\n\n"
  printf "$(tput sgr0)"
  cd "$HOME/repos/github/$folder"
  gitpush
done

