#!/bin/bash

# ensure sudo has been set
# ------------------------
sudo echo "sudo password"

# remove unwanted standard ubuntu folders
# ---------------------------------------
# declare -a rmfldrs=(
# "Desktop"
# "Documents"
# "Downloads"
# "Music"
# "Pictures"
# "Templates"
# "Public"
# "Videos"
# )
# 
# for i in "${rmfldrs[@]}"; do              # loops through array
#   if [ -d "$HOME/$i" ]; then            #if directory
#     echo "removing $i"
#     rmdir "$HOME/$i"
#   fi
# done
# 
# # add new folders
# # ---------------
# declare -a mkfldrs=(
# "desktop"
# "downloads"
# )
# 
# for i in "${mkfldrs[@]}"; do              # loops through array
#   if [ ! -d "$HOME/$i" ]; then            #if not directory
#     echo "adding $i folder"
#     mkdir "$HOME/$i"
#   fi
# done
# 
# # update xdg
# # ----------
# echo "updating xdg user directories"
# xdg-user-dirs-update --set DESKTOP "$HOME"/desktop
# xdg-user-dirs-update --set DOWNLOAD "$HOME"/downloads
# xdg-user-dirs-update


## install Programs
## ----------------
#declare -a programs=(
##"pass"
#"vim"
#"git"
#"shellcheck"
#"tmux"
##"vlc"
##"keepassxc"
#)
#
#for i in "${programs[@]}"; do              # loops through programs array
#  if ! command -v "$i" &>/dev/null; then          # checks if programm not exist
#    echo "installing $i"
#    sudo apt-get install "$i" -y          # installs programm if not exist
#  fi
#done


# git config
# ----------------
#echo 'setting up git config user and email'
#read -r -p 'enter git user email: ' git_email
#read -r -p 'enter git user name: ' git_name
#git config --global user.email "$git_email"
#git config --global user.name "$git_name"

# make repo folders
# ---------------------
if [ ! -d "$HOME/repos/github/" ]; then            #if no directory for repos
    echo "creating home/repos/github/"
    mkdir -p "$HOME"/repos/github && echo "home/repos/github/ has been created"  #make the directory
fi

# clone repos in
# --------------
echo "cloning repos"
declare -a git_repos=(
"git@github.com:gbjnewman/dotfiles.git"
"git@github.com:gbjnewman/utility_scripts.git"
)
if ! command -v git &>/dev/null; then            #if no git
  echo "git not installed"      #echo no git
  echo "installing git"
  sudo apt-get install git      #install git
else
  for i in "${git_repos[@]}"; do              # loops through array
    cd "$HOME"/repos/github/
    git clone $i
  done
fi

# symlink dotfiles
# ---------------
cd "$HOME"/repos/github/dotfiles || exit          #cd to dotfiles or exit
echo "sym linking dotfiles with dotFilesSymlinker"
./dotFilesSymLinker                #run dotFilesSymlinker
