#!/bin/bash

# list of the files and folders to be ignored
ignoreList=(
  "$0"
  ".git/"
  "README.md"
)
# create the $HOME/bin directory if it doesn't already exist
if [ ! -d "$HOME/bin/" ]; then
	mkdir "$HOME/bin/"
fi

# loop though all the files and folders in this directory
for file in *; do
  # if the file is not in the ignore list and the file is not already in the
  # $HOME/bin directory, then...
  if [[ ! " ${ignoreList[*]} " =~ $file && ! -f "$HOME/bin/$file" ]]; then
    # ...symlink the file into $HOME/bin/
    ln -sf "$PWD"/"$file" "$HOME"/bin/"$file"
  fi
done
