#!/bin/bash
#for i in {0..255} ; do
#    printf "\x1b[38;5;%smcolour%s " "${i}" "${i}"
#done
#printf "\n"


for i in {0..255}; do printf "\x1b[38;5;${i}m%3d " $i; if (( ($i + 1) % 16 == 0 )); then echo; fi; done
